const config=window.MYTT;let singlesPlayers=[],doublesTeams=[],playerDb=[];
const TIERS=[{min:-Infinity,name:"Novice",icon:"🌿",cls:"tier-novice",next:1500},{min:1500,name:"Rookie",icon:"🌱",cls:"tier-rookie",next:1600},{min:1600,name:"Challenger",icon:"⚔️",cls:"tier-challenger",next:1700},{min:1700,name:"Elite",icon:"⭐",cls:"tier-elite",next:1800},{min:1800,name:"Master",icon:"🔥",cls:"tier-master",next:1900},{min:1900,name:"Legend",icon:"👑",cls:"tier-legend",next:2000},{min:2000,name:"Grandmaster",icon:"💎",cls:"tier-grandmaster",next:2100},{min:2100,name:"Immortal",icon:"⚡",cls:"tier-immortal",next:2200},{min:2200,name:"MYTT Champion",icon:"🏆",cls:"tier-champion",next:null}];
function getTier(r){const rating=Number(r)||0;let t=TIERS[0];for(const tier of TIERS){if(rating>=tier.min)t=tier}return t}
function tierHTML(r){const t=getTier(r);return `<span class="tier-pill ${t.cls}">${t.icon} ${t.name}</span>`}
function progressHTML(r){const rating=Number(r)||0;const t=getTier(r);if(!t.next)return `<div class="tier-progress"><div class="tier-progress-top"><span>${t.icon} ${t.name}</span><span>Top Tier</span></div><div class="progress-track"><div class="progress-fill" style="width:100%"></div></div><div class="progress-note">You have reached MYTT Champion tier.</div></div>`;const base=t.min===-Infinity?1400:t.min;const pct=Math.max(0,Math.min(100,((rating-base)/(t.next-base))*100));const next=TIERS.find(x=>x.min===t.next);return `<div class="tier-progress"><div class="tier-progress-top"><span>${t.icon} ${t.name}</span><span>${next.icon} ${next.name}</span></div><div class="progress-track"><div class="progress-fill" style="width:${pct}%"></div></div><div class="progress-note">${rating} / ${t.next} · ${t.next-rating} pts to ${next.name}</div></div>`}
function parseCSV(t){const r=[];let row=[],cell="",q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c=='"'&&q&&n=='"'){cell+='"';i++}else if(c=='"'){q=!q}else if(c==","&&!q){row.push(cell.trim());cell=""}else if((c=="\n"||c=="\r")&&!q){if(cell||row.length){row.push(cell.trim());r.push(row);row=[];cell=""}if(c=="\r"&&n=="\n")i++}else cell+=c}if(cell||row.length){row.push(cell.trim());r.push(row)}return r}
function cleanRows(rows){return rows.filter(row=>row.some(cell=>String(cell).trim()!="")).slice(1)}
async function fetchRows(csvUrl){const url=csvUrl+(csvUrl.includes("?")?"&":"?")+"t="+Date.now();const res=await fetch(url);if(!res.ok)throw new Error("Unable to load CSV");return cleanRows(parseCSV(await res.text()))}
function slug(s){return String(s||"").toLowerCase().replace(/[^a-z0-9]+/g,"").trim()}
function rowToLb(row,type){return{type,rank:row[0]||"-",name:row[1]||"-",rating:row[2]||"-",record:row[3]||"-",winRate:row[4]||"-",peak:row[5]||"-"}}
function rowToDb(row){return{id:row[0]||"",name:row[1]||"",grip:row[2]||"",hand:row[3]||"",blade:row[4]||"",fh:row[5]||"",bh:row[6]||"",photo:row[7]||"",status:row[8]||"",joined:row[9]||""}}
function rankLabel(rank){const v=String(rank||"").trim();if(v=="1")return"🥇 1";if(v=="2")return"🥈 2";if(v=="3")return"🥉 3";return v||"-"}
function findDbByName(name){const s=slug(name);return playerDb.find(p=>slug(p.name)===s)||playerDb.find(p=>slug(p.name).includes(s)||s.includes(slug(p.name)))}
function findLbByName(name){const s=slug(name);return singlesPlayers.find(p=>slug(p.name)===s)||singlesPlayers.find(p=>slug(p.name).includes(s)||s.includes(slug(p.name)))||{rating:"1500",peak:"1500",rank:"-",record:"0-0",winRate:"-"}}
function makeRow(item){const tr=document.createElement("tr");tr.className="rank-"+String(item.rank||"").trim();tr.innerHTML=`<td><span class="rank-badge">${rankLabel(item.rank)}</span></td><td class="name" data-player="${encodeURIComponent(item.name)}">${item.name} ↗</td><td>${tierHTML(item.rating)}</td><td class="rating">${item.rating}</td><td>${item.record}</td><td>${item.winRate}</td><td>${item.peak}</td>`;return tr}
async function loadLeaderboard(csvUrl,bodyId,statusId,type,label){const body=document.getElementById(bodyId),status=document.getElementById(statusId);try{const rows=await fetchRows(csvUrl);const items=rows.map(row=>rowToLb(row,type));if(type==="singles")singlesPlayers=items;if(type==="doubles")doublesTeams=items;body.innerHTML="";if(!items.length){body.innerHTML=`<tr><td colspan="7" class="loading">No data yet.</td></tr>`;status.textContent="No data";return}items.forEach(item=>body.appendChild(makeRow(item)));status.textContent="Updated "+new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});renderSearch()}catch(e){console.error(e);body.innerHTML=`<tr><td colspan="7" class="loading">Failed to load ${label} leaderboard.</td></tr>`;status.textContent="Load failed"}}
async function loadPlayerDb(){try{const rows=await fetchRows(config.playerDbCsv);const all=rows.map(rowToDb).filter(p=>p.name);playerDb=all.filter(p=>String(p.status).toLowerCase()==="approved");if(!playerDb.length)playerDb=all;renderPlayers()}catch(e){console.error(e);renderPlayers()}}
function playerItem(name){const db=findDbByName(name);const lb=findLbByName(db?.name||name);return{db,lb,name:db?.name||name}}
function openProfile(name){const {db,lb,name:playerName}=playerItem(decodeURIComponent(name));document.getElementById("profileContent").innerHTML=`<div class="profile-top"><div class="profile-avatar">👤</div><div><h3>${playerName}</h3><p>${db?.id||"MYTT Player"} · Rank #${lb.rank}</p>${tierHTML(lb.rating)}</div></div><div class="profile-stats"><div class="stat"><small>Current Rating</small><strong>${lb.rating}</strong></div><div class="stat"><small>Peak Rating</small><strong>${lb.peak}</strong></div><div class="stat"><small>Record</small><strong>${lb.record}</strong></div><div class="stat"><small>Win Rate</small><strong>${lb.winRate}</strong></div></div>${progressHTML(lb.rating)}<div class="profile-panel"><h3>🏓 Player Info</h3><div class="equipment-row"><small>Grip</small><strong>${db?.grip||"-"}</strong></div><div class="equipment-row"><small>Hand</small><strong>${db?.hand||"-"}</strong></div><div class="equipment-row"><small>Blade</small><strong>${db?.blade||"-"}</strong></div><div class="equipment-row"><small>FH Rubber</small><strong>${db?.fh||"-"}</strong></div><div class="equipment-row"><small>BH Rubber</small><strong>${db?.bh||"-"}</strong></div><div class="equipment-row"><small>Member Since</small><strong>${db?.joined||"-"}</strong></div></div><div class="future-grid"><div class="future-card">📈 Rating History<br><small>Coming soon</small></div><div class="future-card">🕒 Recent Matches<br><small>Coming soon</small></div><div class="future-card">🤝 Head to Head<br><small>Coming soon</small></div></div>`;document.getElementById("profileModal").classList.remove("hidden")}
function closeProfile(){document.getElementById("profileModal").classList.add("hidden")}
function renderPlayers(){const grid=document.getElementById("playersGrid");if(!grid)return;if(!playerDb.length){grid.innerHTML=`<p class="loading">No approved players yet. Change Status to Approved in Player Database.</p>`;return}grid.innerHTML=playerDb.map(p=>{const lb=findLbByName(p.name);return `<div class="player-card" data-player="${encodeURIComponent(p.name)}"><div class="player-card-top"><div class="avatar">👤</div><div><h3>${p.name}</h3><p>${p.id}</p>${tierHTML(lb.rating)}</div></div><p>⭐ Rating ${lb.rating} · Peak ${lb.peak}</p><p>🏓 ${p.grip||"-"} · ${p.hand||"-"}</p></div>`}).join("")}
function renderSearch(){const input=document.getElementById("globalSearch"),results=document.getElementById("searchResults");if(!input||!results)return;const q=input.value.trim().toLowerCase();if(!q){results.innerHTML=`<p class="muted">Type a player name to view rating, tier and profile.</p>`;return}const seen=new Set();const items=[...singlesPlayers,...playerDb.map(p=>{const lb=findLbByName(p.name);return{...lb,name:p.name,label:"Registered Player"}})].filter(i=>i.name.toLowerCase().includes(q)).filter(i=>{const k=slug(i.name);if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);if(!items.length){results.innerHTML=`<p class="muted">No player found.</p>`;return}results.innerHTML=items.map(i=>`<div class="search-result" data-player="${encodeURIComponent(i.name)}"><div class="search-rank">${rankLabel(i.rank)}</div><div><div class="search-name">${i.name}</div><div class="search-meta">${tierHTML(i.rating)} · W-L ${i.record} · Peak ${i.peak}</div></div><div class="search-rating">${i.rating}</div></div>`).join("")}
function bindEvents(){document.addEventListener("input",e=>{if(e.target.id==="globalSearch")renderSearch()});document.addEventListener("click",e=>{const p=e.target.closest("[data-player]");if(p)openProfile(p.dataset.player);if(e.target.matches("[data-close-modal]"))closeProfile()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeProfile()})}
async function loadAll(){await loadPlayerDb();await loadLeaderboard(config.singlesCsv,"singlesBody","singlesStatus","singles","singles");await loadLeaderboard(config.doublesCsv,"doublesBody","doublesStatus","doubles","doubles");renderPlayers();renderSearch()}
bindEvents();loadAll();setInterval(loadAll,60000);